avx:
	make -C ../AVX avx-4th avx-6th avx-8th
	cp ../AVX/avx-?th ./

avx2:
	make -C ../AVX2 avx2-4th avx2-6th avx2-8th
	cp ../AVX2/avx2-?th ./

mic:
	make -C ../MIC mic-4th mic-6th mic-8th
	cp ../MIC/mic-?th ./

